mkdir -p ~/.vim/bundle/vaxe/ultisnips
ULTISNIPS_OUTPUT=~/.vim/bundle/vaxe/ultisnips/haxe.snippets
python ~/.vim/bundle/Ultisnips/utils/convert_snipmate_snippets.py ~/.vim/bundle/vaxe/snippets/haxe.snippets  > $ULTISNIPS_OUTPUT
echo '# This file is autogenerated by tools/create_ultisnips.sh, any edits will be overwritten.
# (Edit vaxe/snippets/haxe.snippets instead.)' | cat - $ULTISNIPS_OUTPUT > temp && mv temp $ULTISNIPS_OUTPUT

